import java.util.*;
public final class Problem2 implements EulerProblems{
	public static void main(String[] args) {
		System.out.println(new Problem2().run());
	}
	//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
   //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	public String run() {
		int a = 1;
		int b = 2;
		int c = 0;
		int sum = 2;
		while(c <= 4e6) {
			c = a+b;
			a = b;
			b = c;
			if(c % 2 == 0) {
				sum = sum + c;
			}
		}
		return Integer.toString(sum);
		
	}
}
